export default [
  {
    id: "C1",
    alimentos: [
      "170ML DE CAFÉ COM CANELA EM PÓ E ADOÇANTE TIPO STEVIA 100% A GOSTO",
      "2 OVOS MEXIDOS COM 1 COLHER DE CHÁ DE SEMENTES DE CHIA + 1 FATIA MÉDIA DE QUEIJO MUSSARELA (20G)",
      "1 KIWI, 2 FATIAS DE ABACAXI, 1 FATIA DE MELÃO OU TANGERINA",
    ],
  },
  {
    id: "C2",
    alimentos: [
      "170ML DE CAFÉ COM CANELA EM PÓ E ADOÇANTE TIPO STEVIA 100% A GOSTO E NO MÁXIMO 1 COLHER DE SOBREMESA RASA DE LEITE EM PÓ ZERO LACTOSE",
      "2 OVOS MEXIDOS + ORÉGANO + 1 COLHER DE CHÁ DE SEMENTES DE CHIA, SAL E TEMPEROS NATURAIS A GOSTO PREPARADO NA MANTEIGA",
      "1 FATIA DE PÃO INTEGRAL",
    ],
  },
  {
    id: "C3",
    alimentos: [
      "170ML DE CAFÉ COM CANELA EM PÓ E ADOÇANTE TIPO STEVIA 100% A GOSTO",
      "2 OVOS MEXIDOS COM 1 COLHER DE CHÁ DE SEMENTES DE CHIA + 1 FATIA MÉDIA DE QUEIJO MUSSARELA (20G)",
      "1 KIWI, 2 FATIAS DE ABACAXI, 1 FATIA DE MELÃO OU TANGERINA",
    ],
  },
  {
    id: "C4",
    alimentos: [
      "170ML DE CAFÉ COM CANELA EM PÓ E ADOÇANTE TIPO STEVIA 100% À GOSTO E NO MÁXIMO 1 COLHER DE SOBREMESA RASA DE LEITE EM PÓ ZERO LACTOSE",
      "100G DE CUSCUZ DE MILHO COM MANTEIGA  (SEMENTES DE CHIA NA MASSA)",
      "2 OVOS MEXIDOS (PODERÁ SUBSTITUIR 1 OVO POR 25G DE QUEIJO MUSSARELA)",
    ],
  },
  {
    id: "C5",
    alimentos: [
      "170ML DE CAFÉ COM CANELA EM PÓ E ADOÇANTE TIPO STEVIA 100% A GOSTO",
      "2 OVOS MEXIDOS COM 1 COLHER DE CHÁ DE SEMENTES DE CHIA + 1 FATIA MÉDIA DE QUEIJO MUSSARELA (20G)",
      "1 KIWI, 2 FATIAS DE ABACAXI, 1 FATIA DE MELÃO OU TANGERINA",
    ],
  },
  {
    id: "C6",
    alimentos: [
      "170ML DE CAFÉ COM CANELA EM PÓ E ADOÇANTE TIPO STEVIA 100% À GOSTO E NO MÁXIMO 1 COLHER DE SOBREMESA RASA DE LEITE EM PÓ ZERO LACTOSE",
      "1 OVO + 30G DE QUEIJO COALHO OU MUSSARELA",
      "1 TAPIOCA MÉDIA (60G) E ACRESCENTAR 1 COLHER DE CHÁ DE SEMENTES DE CHIA NA MASSA",
    ],
  },
  {
    id: "C7",
    alimentos: [
      "170ML DE CAFÉ COM CANELA EM PÓ E ADOÇANTE TIPO STEVIA 100% À GOSTO E NO MÁXIMO 1 COLHER DE SOBREMESA RASA DE LEITE EM PÓ ZERO LACTOSE",
      "2 OVOS MEXIDOS + ORÉGANO + 1 COLHER DE CHÁ DE SEMENTES DE CHIA, SAL E TEMPEROS NATURAIS A GOSTO PREPARADO NA MANTEIGA",
      "1 FATIA DE PÃO INTEGRAL",
    ],
  },
  {
    id: "LM1",
    alimentos: ["10 CASTANHAS DE CAJU"],
  },
  {
    id: "LM2",
    alimentos: ["5 CASTANHAS DE CAJÚ + 2 CASTANHAS DO PARÁ"],
  },
  {
    id: "LM3",
    alimentos: [
      "3 CASTANHAS DO PARÁ + 1 COLHER DE SOBREMESA RASA DE SEMENTES DE ABÓBORA",
    ],
  },
  {
    id: "LM4",
    alimentos: ["10 CASTANHAS DE CAJU"],
  },
  {
    id: "LM5",
    alimentos: ["5 CASTANHAS DE CAJÚ + 2 CASTANHAS DO PARÁ"],
  },
  {
    id: "LM6",
    alimentos: [
      "3 CASTANHAS DO PARÁ + 1 COLHER DE SOBREMESA RASA DE SEMENTES DE ABÓBORA",
    ],
  },
  {
    id: "LM7",
    alimentos: ["10 CASTANHAS DE CAJU"],
  },
  {
    id: "A1",
    alimentos: [
      "4 COLHERES DE SOPA DE PURÊ DE MACAXEIRA, BATATA INGLESA OU MANDIOQUINHA (GRUPO C – 120G)",
      "SALADA DE CENOURA, REPOLHO E CHEIRO VERDE REFOGADO (2 COLHERES GRANDES)",
      "COUVE FOLHA OU ESPINAFRE REFOGADO COM TOMATE, ALHO E CEBOLA ROXA A VONTADE OU SALADA GRUPO A A VONTADE",
      "PEIXE OU FRANGO ASSADO OU GRELHADO (2 BIFES OU POSTAS PEQUENAS – 120G)",
      "MOLHO DA SALADA: VINAGRE BALSÂMICO, SAL ROSA, LIMÃO, ORÉGANO E AZEITE EXTRAVIRGEM",
      "REGAR A SALADA OU CARNE COM 1 COLHER DE SOPA RASA DE VINAGRE DE MAÇA + 1 COLHER DE SOBREMESA CHEIA DE AZEITE DE OLIVIA EXTRAVIRGEM",
      "SOBREMESA: 100ML DE ÁGUA + SUCO DE 1 LIMÃO PEQUENO - CHÁ DE HORTELÃ OU ERVA DOCE",
      "GRUPO A: (A VONTADE) ABOBRINHA, ALFACE, BERINJELA, BRÓCOLIS, CEBOLA, CEBOLINHA, COUVE, PALMITO, PEPINO, PIMENTÃO, REPOLHO, TOMATE",
      "GRUPO C: (COM MODERAÇÃO DE ACORDO COM O PLANO) BATATA INGLESA, BATATA DOCE, MANDIOCA, MILHO VERDE",
    ],
  },
  {
    id: "A2",
    alimentos: [
      "3 COLHERES DE SERVIR DE ARROZ (90G)",
      "3 COLHERES DE SOPA CHEIAS DE CENOURA E BETERRABA CRUAS E RALADAS",
      "REPOLHO E CENOURA REFOGADOS COM TOMATE, ALHO E CEBOLA ROXA A VONTADE OU ALFACE, TOMATE E CEBOLA ROXA A VONTADE",
      "CARNE BOVINA OU FRANGO ASSADO OU GRELHADO (1 BIFE MÉDIO – 120G)",
      "MOLHO DA SALADA: VINAGRE BALSÂMICO, SAL ROSA, LIMÃO, ORÉGANO E AZEITE EXTRAVIRGEM",
      "REGAR A SALADA OU CARNE COM 1 COLHER DE SOPA RASA DE VINAGRE DE MAÇA + 1 COLHER DE SOBREMESA CHEIA DE AZEITE DE OLIVIA EXTRAVIRGEM",
      "SOBREMESA: 1 LARANJA OU 1 TANGERINA - CHÁ DE BOLDO",
    ],
  },
  {
    id: "A3",
    alimentos: [
      "3 COLHERES DE SERVIR DE ARROZ (90G) OU 120G DE BATATA DOCE COZIDA",
      "3 COLHERES DE SOPA CHEIAS DE VEGETAIS GRUPO B COZIDOS OU NO VAPOR (BETERRABA, VAGEM, CHUCHU E/OU CENOURA – 70G)",
      "COUVE FOLHA REFOGADO COM TOMATE, ALHO E CEBOLA ROXA A VONTADE OU SALADA GRUPO A VONTADE",
      "CARNE BOVINA OU FRANGO AO MOLHO (2 COLHERES DE SERVIR – 100G) + 1 OVO COZIDO",
      "MOLHO DA SALADA: VINAGRE BALSÂMICO, SAL ROSA, LIMÃO, ORÉGANO E AZEITE EXTRAVIRGEM",
      "REGAR A SALADA OU CARNE COM 1 COLHER DE SOPA RASA DE VINAGRE DE MAÇA + 1 COLHER DE SOBREMESA CHEIA DE AZEITE DE OLIVIA EXTRAVIRGEM",
      "SOBREMESA: 100ML DE ÁGUA + SUCO DE 1 LIMÃO PEQUENO - CHÁ DE HORTELÃ OU GENGIBRE",
      "GRUPO A: (A VONTADE) ABOBRINHA, ALFACE, BERINJELA, BRÓCOLIS, CEBOLA, CEBOLINHA, COUVE, PALMITO, PEPINO, PIMENTÃO, REPOLHO, TOMATE",
      "GRUPO B: (DE ACORDO COM O PLANO) ABÓBORA, BETERRABA, CENOURA, CHUCHU, ERVILHA VERDE",
    ],
  },
  {
    id: "A4",
    alimentos: [
      "4 COLHERES DE SOPA DE PURÊ DE MACAXEIRA, BATATA INGLESA OU MANDIOQUINHA (GRUPO C – 120G)",
      "SALADA DE CENOURA, REPOLHO E CHEIRO VERDE REFOGADO (2 COLHERES GRANDES)",
      "COUVE FOLHA OU ESPINAFRE REFOGADO COM TOMATE, ALHO E CEBOLA ROXA A VONTADE OU SALADA GRUPO A A VONTADE",
      "PEIXE OU FRANGO ASSADO OU GRELHADO (2 BIFES OU POSTAS PEQUENAS – 120G)",
      "MOLHO DA SALADA: VINAGRE BALSÂMICO, SAL ROSA, LIMÃO, ORÉGANO E AZEITE EXTRAVIRGEM",
      "REGAR A SALADA OU CARNE COM 1 COLHER DE SOPA RASA DE VINAGRE DE MAÇA + 1 COLHER DE SOBREMESA CHEIA DE AZEITE DE OLIVIA EXTRAVIRGEM",
      "SOBREMESA: 100ML DE ÁGUA + SUCO DE 1 LIMÃO PEQUENO - CHÁ DE HORTELÃ OU ERVA DOCE",
      "GRUPO A: (A VONTADE) ABOBRINHA, ALFACE, BERINJELA, BRÓCOLIS, CEBOLA, CEBOLINHA, COUVE, PALMITO, PEPINO, PIMENTÃO, REPOLHO, TOMATE",
      "GRUPO C: (COM MODERAÇÃO DE ACORDO COM O PLANO) BATATA INGLESA, BATATA DOCE, MANDIOCA, MILHO VERDE",
    ],
  },
  {
    id: "A5",
    alimentos: [
      "3 COLHERES DE SERVIR DE ARROZ (90G)",
      "3 COLHERES DE SOPA CHEIAS DE CENOURA E BETERRABA CRUAS E RALADAS",
      "REPOLHO E CENOURA REFOGADOS COM TOMATE, ALHO E CEBOLA ROXA A VONTADE OU ALFACE, TOMATE E CEBOLA ROXA A VONTADE",
      "CARNE BOVINA OU FRANGO ASSADO OU GRELHADO (1 BIFE MÉDIO – 120G)",
      "MOLHO DA SALADA: VINAGRE BALSÂMICO, SAL ROSA, LIMÃO, ORÉGANO E AZEITE EXTRAVIRGEM",
      "REGAR A SALADA OU CARNE COM 1 COLHER DE SOPA RASA DE VINAGRE DE MAÇA + 1 COLHER DE SOBREMESA CHEIA DE AZEITE DE OLIVIA EXTRAVIRGEM",
      "SOBREMESA: 1 LARANJA OU 1 TANGERINA - CHÁ DE BOLDO",
    ],
  },
  {
    id: "A6",
    alimentos: [
      "3 COLHERES DE SERVIR DE ARROZ (90G) OU 120G DE BATATA DOCE COZIDA",
      "3 COLHERES DE SOPA CHEIAS DE VEGETAIS GRUPO B COZIDOS OU NO VAPOR (BETERRABA, VAGEM, CHUCHU E/OU CENOURA – 70G)",
      "COUVE FOLHA REFOGADO COM TOMATE, ALHO E CEBOLA ROXA A VONTADE OU SALADA GRUPO A VONTADE",
      "CARNE BOVINA OU FRANGO AO MOLHO (2 COLHERES DE SERVIR – 100G) + 1 OVO COZIDO",
      "MOLHO DA SALADA: VINAGRE BALSÂMICO, SAL ROSA, LIMÃO, ORÉGANO E AZEITE EXTRAVIRGEM",
      "REGAR A SALADA OU CARNE COM 1 COLHER DE SOPA RASA DE VINAGRE DE MAÇA + 1 COLHER DE SOBREMESA CHEIA DE AZEITE DE OLIVIA EXTRAVIRGEM",
      "SOBREMESA: 100ML DE ÁGUA + SUCO DE 1 LIMÃO PEQUENO - CHÁ DE HORTELÃ OU GENGIBRE",
      "GRUPO A: (A VONTADE) ABOBRINHA, ALFACE, BERINJELA, BRÓCOLIS, CEBOLA, CEBOLINHA, COUVE, PALMITO, PEPINO, PIMENTÃO, REPOLHO, TOMATE",
      "GRUPO B: (DE ACORDO COM O PLANO) ABÓBORA, BETERRABA, CENOURA, CHUCHU, ERVILHA VERDE",
    ],
  },
  {
    id: "A7",
    alimentos: [
      "4 COLHERES DE SOPA DE PURÊ DE MACAXEIRA, BATATA INGLESA OU MANDIOQUINHA (GRUPO C – 120G)",
      "SALADA DE CENOURA, REPOLHO E CHEIRO VERDE REFOGADO (2 COLHERES GRANDES)",
      "COUVE FOLHA OU ESPINAFRE REFOGADO COM TOMATE, ALHO E CEBOLA ROXA A VONTADE OU SALADA GRUPO A VONTADE",
      "PEIXE OU FRANGO ASSADO OU GRELHADO (2 BIFES OU POSTAS PEQUENAS – 120G)",
      "MOLHO DA SALADA: VINAGRE BALSÂMICO, SAL ROSA, LIMÃO, ORÉGANO E AZEITE EXTRAVIRGEM",
      "REGAR A SALADA OU CARNE COM 1 COLHER DE SOPA RASA DE VINAGRE DE MAÇA + 1 COLHER DE SOBREMESA  CHEIA DE AZEITE DE OLIVIA EXTRAVIRGEM",
      "SOBREMESA: 100ML DE ÁGUA + SUCO DE 1 LIMÃO PEQUENO - CHÁ DE HORTELÃ OU ERVA DOCE",
      "GRUPO A: (A VONTADE) ABOBRINHA, ALFACE, BERINJELA, BRÓCOLIS, CEBOLA, CEBOLINHA, COUVE, PALMITO, PEPINO, PIMENTÃO, REPOLHO, TOMATE",
      "GRUPO C: (COM MODERAÇÃO DE ACORDO COM O PLANO) BATATA INGLESA, BATATA DOCE, MANDIOCA, MILHO VERDE",
    ],
  },
  {
    id: "LT1",
    alimentos: ["5G DE CREATINA BATIDO EM 200ML DE ÁGUA"],
  },
  {
    id: "LT2",
    alimentos: [
      "5G DE CREATINA BATIDO EM 200ML DE ÁGUA",
      "30 G DE WHEY BATIDO COM 1 BANANA E ÁGUA GELADA",
    ],
  },
  {
    id: "LT3",
    alimentos: [
      "5G DE CREATINA BATIDO EM 200ML DE ÁGUA",
      "2 FATIAS DE PÃO INTEGRAL + 2 COLHERES DE SOPA CHEIA DE PATÊ CASEIRO DE ATUM OU FRANGO + 1 COLHER DE SOPA DE CREME DE RICOTA",
    ],
  },
  {
    id: "LT4",
    alimentos: [
      "5G DE CREATINA BATIDO EM 200ML DE ÁGUA",
      "30 G DE WHEY BATIDO COM 1 POLPA DE FRUTA CONGELADA (MORANGO, AMORA, GOIABA, ETC) + ÁGUA",
    ],
  },
  {
    id: "LT5",
    alimentos: [
      "5G DE CREATINA BATIDO EM 200ML DE ÁGUA",
      "1 CUSCUZ DE MILHO PEITINHO (120G) + 2 OVOS MEXIDOS COM 2 COLHERES DE SERVIR DE FRANGO DESFIADO (60G) + TOMATE, CEBOLA E TEMPEROS NATURAIS",
    ],
  },
  {
    id: "LT6",
    alimentos: [
      "5G DE CREATINA BATIDO EM 200ML DE ÁGUA",
      "250G DE IOGURTE COM WHEY - 23G A 26G DE PROTEÍNA",
    ],
  },
  {
    id: "LT7",
    alimentos: [
      "5G DE CREATINA BATIDO EM 200ML DE ÁGUA",
      "30 G DE WHEY BATIDO COM 1 BANANA E ÁGUA GELADA",
    ],
  },
  {
    id: "J1",
    alimentos: [
      "OMELETE DE 3 OVOS COM 4 COLHERES DE SOPA DE ATUM OU FRANGO DESFIADO + ESPINAFRE + CENOURA + CHEIRO VERDE + SAL E TEMPERO SECO (PODE FAZER OS OVOS MEXIDOS COM CARNE SECA OU FRANGO DESFIADO TAMBÉM)",
    ],
  },
  {
    id: "J2",
    alimentos: [
      "150G DE CARNE, PEIXE OU FRANGO",
      "SALADA DE VEGETAIS GRUPO A (FOLHAS A VONTADE + TOMATE, CEBOLA, PEPINO, CENOURA RALADA ETC.)",
      "FIO DE AZEITE EXTRAVIRGEM",
      "GRUPO A: (A VONTADE) ABOBRINHA, ALFACE, BERINJELA, BRÓCOLIS, CEBOLA, CEBOLINHA, COUVE, PALMITO, PEPINO, PIMENTÃO, REPOLHO, TOMATE",
    ],
  },
  {
    id: "J3",
    alimentos: [
      "ESPAGUETE DE ABOBRINHA COM CENOURA A VONTADE",
      "7 COLHERES DE SOPA DE CARNE MOÍDA – 140G",
    ],
  },
  {
    id: "J4",
    alimentos: [
      "OMELETE DE 3 OVOS COM 4 COLHERES DE SOPA DE ATUM OU FRANGO DESFIADO + ESPINAFRE + CENOURA + CHEIRO VERDE + SAL E TEMPERO SECO (PODE FAZER OS OVOS MEXIDOS COM CARNE SECA OU FRANGO DESFIADO TAMBÉM)",
    ],
  },
  {
    id: "J5",
    alimentos: [
      "150G DE CARNE, PEIXE OU FRANGO",
      "SALADA DE VEGETAIS GRUPO A (FOLHAS A VONTADE + TOMATE, CEBOLA, PEPINO, CENOURA RALADA ETC.)",
      "FIO DE AZEITE EXTRAVIRGEM",
      "GRUPO A: (A VONTADE) ABOBRINHA, ALFACE, BERINJELA, BRÓCOLIS, CEBOLA, CEBOLINHA, COUVE, PALMITO, PEPINO, PIMENTÃO, REPOLHO, TOMATE",
    ],
  },
  {
    id: "J6",
    alimentos: [
      "ESPAGUETE DE ABOBRINHA COM CENOURA A VONTADE",
      "7 COLHERES DE SOPA DE CARNE MOÍDA – 140G",
    ],
  },
  {
    id: "J7",
    alimentos: [
      "OMELETE DE 3 OVOS COM 4 COLHERES DE SOPA DE ATUM OU FRANGO DESFIADO + ESPINAFRE + CENOURA + CHEIRO VERDE + SAL E TEMPERO SECO (PODE FAZER OS OVOS MEXIDOS COM CARNE SECA OU FRANGO DESFIADO TAMBÉM)",
    ],
  },
];
