export default [
  {
    id: "C1",
    alimentos: [
      "170ML DE CAFÉ COM CANELA EM PÓ E ADOÇANTE TIPO STEVIA 100% À GOSTO",
      "2 OVOS MEXIDOS COM 1 COLHER DE CHÁ DE SEMENTES DE CHIA + 1 FATIA MÉDIA DE QUEIJO MUSSARELA (20G)",
      "1 KIWI, 2 FATIAS DE ABACAXI, 1 FATIA DE MELÃO OU 1 TANGERINA",
    ],
  },
  {
    id: "C2",
    alimentos: [
      "170ML DE CAFÉ COM CANELA EM PÓ E ADOÇANTE TIPO STEVIA 100% À GOSTO E NO MÁXIMO 1 COLHER DE SOBREMESA RASA DE LEITE EM PÓ ZERO LACTOSE",
      "2 OVOS MEXIDOS + ORÉGANO + 1 COLHER DE CHÁ DE SEMENTES DE CHIA, SAL E TEMPEROS NATURAIS A GOSTO – PREPARAR NA MANTEIGA",
      "1 FATIA DE PÃO INTEGRAL",
    ],
  },
  {
    id: "C3",
    alimentos: [
      "170ML DE CAFÉ COM CANELA EM PÓ E ADOÇANTE TIPO STEVIA 100% À GOSTO",
      "2 OVOS MEXIDOS COM 1 COLHER DE CHÁ DE SEMENTES DE CHIA + 1 FATIA MÉDIA DE QUEIJO MUSSARELA (20G)",
      "1 KIWI, 2 FATIAS DE ABACAXI, 1 FATIA DE MELÃO OU 1 TANGERINA",
    ],
  },
  {
    id: "C4",
    alimentos: [
      "170ML DE CAFÉ COM CANELA EM PÓ E ADOÇANTE TIPO STEVIA 100% À GOSTO E NO MÁXIMO 1 COLHER DE SOBREMESA RASA DE LEITE EM PÓ ZERO LACTOSE",
      "100G DE CUSCUZ DE MILHO COM MANTEIGA",
      "2 OVOS MEXIDOS (PODERÁ SUBSTITUIR 1 OVO POR 25G DE QUEIJO MUSSARELA)",
    ],
  },
  {
    id: "C5",
    alimentos: [
      "170ML DE CAFÉ COM CANELA EM PÓ E ADOÇANTE TIPO STEVIA 100% À GOSTO",
      "2 OVOS MEXIDOS COM 1 COLHER DE CHÁ DE SEMENTES DE CHIA + 1 FATIA MÉDIA DE QUEIJO MUSSARELA (20G)",
      "1 KIWI, 2 FATIAS DE ABACAXI, 1 FATIA DE MELÃO OU 1 TANGERINA",
    ],
  },
  {
    id: "C6",
    alimentos: [
      "170ML DE CAFÉ COM CANELA EM PÓ E ADOÇANTE TIPO STEVIA 100% À GOSTO E NO MÁXIMO 1 COLHER DE SOBREMESA RASA DE LEITE EM PÓ ZERO LACTOSE",
      "1 OVO + 30G DE QUEIJO COALHO OU MUSSARELA",
      "1 TAPIOCA MÉDIA (60G) E ACRESCENTAR 1 COLHER DE CHÁ DE SEMENTES DE CHIA NA MASSA",
    ],
  },
  {
    id: "C7",
    alimentos: [
      "170ML DE CAFÉ COM CANELA EM PÓ E ADOÇANTE TIPO STEVIA 100% À GOSTO E NO MÁXIMO 1 COLHER DE SOBREMESA RASA DE LEITE EM PÓ ZERO LACTOSE",
      "2 OVOS MEXIDOS + ORÉGANO + 1 COLHER DE CHÁ DE SEMENTES DE CHIA, SAL E TEMPEROS NATURAIS A GOSTO – PREPARAR NA MANTEIGA",
      "1 FATIA DE PÃO INTEGRAL",
    ],
  },
  {
    id: "LM1",
    alimentos: ["10 CASTANHAS DE CAJU", "2 OVOS COZIDOS OU 50G DE CARNE MOÍDA"],
  },
  {
    id: "LM2",
    alimentos: [
      "5 CASTANHAS DE CAJU + 2 CASTANHAS DO PARÁ",
      "15G DE WHEY BATIDO EM ÁGUA",
    ],
  },
  {
    id: "LM3",
    alimentos: [
      "250ML DE IOGURTE COM WHEY ZERO LACTOSE (18 A 23G DE PROTEÍNA NA PORÇÃO)",
    ],
  },
  {
    id: "LM4",
    alimentos: ["10 CASTANHAS DE CAJU", "2 OVOS COZIDOS OU 50G DE CARNE MOÍDA"],
  },
  {
    id: "LM5",
    alimentos: [
      "5 CASTANHAS DE CAJU + 2 CASTANHAS DO PARÁ",
      "15G DE WHEY BATIDO EM ÁGUA",
    ],
  },
  {
    id: "LM6",
    alimentos: [
      "250ML DE IOGURTE COM WHEY ZERO LACTOSE (18 A 23G DE PROTEÍNA NA PORÇÃO)",
    ],
  },
  {
    id: "LM7",
    alimentos: ["10 CASTANHAS DE CAJU", "2 OVOS COZIDOS OU 50G DE CARNE MOÍDA"],
  },
  {
    id: "A1",
    alimentos: [
      "3 COLHERES DE SOPA DE PURÊ DE MACAXEIRA, BATATA INGLESA OU MANDIOQUINHA (GRUPO C – 90G)",
      "SALADA DE CENOURA, REPOLHO E CHEIRO VERDE REFOGADO (2 COLHERES GRANDES)",
      "COUVE FOLHA OU ESPINAFRE REFOGADOS COM TOMATE, ALHO E CEBOLA ROXA A VONTADE OU SALADA GRUPO A À VONTADE",
      "PEIXE OU FRANGO ASSADO OU GRELHADO (2 BIFES OU POSTAS PEQUENAS-120G)",
      "MOLHO DA SALADA: VINAGRE BALSAMICO, SAL ROSA, LIMÃO, ORÉGANO E AZEITE EXTRAVIRGEM OBS.: EVITAR FRITURA",
      "SOBREMESA: 100ML DE ÁGUA + SUCO DE 1 LIMÃO PEQUENO - CHÁ DE HORTELÃ OU ERVA DOCE",
      "GRUPO A: (A VONTADE) ABOBRINHA, ALFACE, BERINJELA, BRÓCOLIS, CEBOLA, CEBOLINHA, COUVE, PALMITO, PEPINO, PIMENTÃO, REPOLHO, TOMATE",
      "GRUPO C: (COM MODERAÇÃO DE ACORDO COM O PLANO) BATATA INGLESA, BATATA DOCE, MANDIOCA, MILHO VERDE",
    ],
  },
  {
    id: "A2",
    alimentos: [
      "2,5 COLHERES DE SERVIR DE ARROZ (75G)",
      "3 COLHERES DE SOPA CHEIAS DE CENOURA E BETERRABA CRUAS E RALADAS",
      "REPOLHO E CENOURA REFOGADOS COM TOMATE, ALHO E CEBOLA ROXA A VONTADE OU ALFACES, TOMATE E CEBOLA ROXA A VONTADE",
      "CARNE BOVINA OU FRANGO ASSADO OU GRELHADO (1 BIFE MÉDIO -120G)",
      "MOLHO DA SALADA: VINAGRE BALSAMICO, SAL ROSA, LIMÃO, ORÉGANO E AZEITE EXTRAVIRGEM OBS.: EVITAR FRITURA",
      "SOBREMESA: 1 LARANJA OU 1 TANGERINA - CHÁ DE BOLDO",
    ],
  },
  {
    id: "A3",
    alimentos: [
      "2 COLHERES DE SERVIR DE ARROZ (75G) OU 100G DE BATATA DOCE COZIDA",
      "3 COLHERES DE SOPA CHEIAS DE VEGETAIS GRUPO B COZIDOS OU NO VAPOR (BETERRABA, VAGEM, CHUCHU E/OU CENOURA – 70G)",
      "COUVE FOLHA REFOGADO COM TOMATE, ALHO E CEBOLA ROXA A VONTADE OU SALADA GRUPO A À VONTADE",
      "CARNE BOVINA OU FRANGO AO MOLHO (2 COLHERES DE SERVIR – 100G) + 1 OVO COZIDO",
      "MOLHO DA SALADA: VINAGRE BALSAMICO, SAL ROSA, LIMÃO, ORÉGANO E AZEITE EXTRAVIRGEM OBS.: EVITAR FRITURA",
      "SOBREMESA: 100ML DE ÁGUA + SUCO DE 1 LIMÃO PEQUENO - CHÁ DE HORTELÃ OU GENGIBRE",
      "GRUPO A: (A VONTADE) ABOBRINHA, ALFACE, BERINJELA, BRÓCOLIS, CEBOLA, CEBOLINHA, COUVE, PALMITO, PEPINO, PIMENTÃO, REPOLHO, TOMATE",
      "GRUPO B: (DE ACORDO COM O PLANO) ABÓBORA, BETERRABA, CENOURA, CHUCHU, ERVILHA VERDE",
    ],
  },
  {
    id: "A4",
    alimentos: [
      "3 COLHERES DE SOPA DE PURÊ DE MACAXEIRA, BATATA INGLESA OU MANDIOQUINHA (GRUPO C – 90G)",
      "SALADA DE CENOURA, REPOLHO E CHEIRO VERDE REFOGADO (2 COLHERES GRANDES)",
      "COUVE FOLHA OU ESPINAFRE REFOGADOS COM TOMATE, ALHO E CEBOLA ROXA A VONTADE OU SALADA GRUPO A À VONTADE",
      "PEIXE OU FRANGO ASSADO OU GRELHADO (2 BIFES OU POSTAS PEQUENAS-120G)",
      "MOLHO DA SALADA: VINAGRE BALSAMICO, SAL ROSA, LIMÃO, ORÉGANO E AZEITE EXTRAVIRGEM OBS.: EVITAR FRITURA",
      "SOBREMESA: 100ML DE ÁGUA + SUCO DE 1 LIMÃO PEQUENO - CHÁ DE HORTELÃ OU ERVA DOCE",
      "GRUPO A: (A VONTADE) ABOBRINHA, ALFACE, BERINJELA, BRÓCOLIS, CEBOLA, CEBOLINHA, COUVE, PALMITO, PEPINO, PIMENTÃO, REPOLHO, TOMATE",
      "GRUPO C: (COM MODERAÇÃO DE ACORDO COM O PLANO) BATATA INGLESA, BATATA DOCE, MANDIOCA, MILHO VERDE",
    ],
  },
  {
    id: "A5",
    alimentos: [
      "2,5 COLHERES DE SERVIR DE ARROZ (75G)",
      "3 COLHERES DE SOPA CHEIAS DE CENOURA E BETERRABA CRUAS E RALADAS",
      "REPOLHO E CENOURA REFOGADOS COM TOMATE, ALHO E CEBOLA ROXA A VONTADE OU ALFACES, TOMATE E CEBOLA ROXA A VONTADE",
      "CARNE BOVINA OU FRANGO ASSADO OU GRELHADO (1 BIFE MÉDIO -120G)",
      "MOLHO DA SALADA: VINAGRE BALSAMICO, SAL ROSA, LIMÃO, ORÉGANO E AZEITE EXTRAVIRGEM OBS.: EVITAR FRITURA",
      "SOBREMESA: 1 LARANJA OU 1 TANGERINA - CHÁ DE BOLDO",
    ],
  },
  {
    id: "A6",
    alimentos: [
      "2 COLHERES DE SERVIR DE ARROZ (75G) OU 100G DE BATATA DOCE COZIDA",
      "3 COLHERES DE SOPA CHEIAS DE VEGETAIS GRUPO B COZIDOS OU NO VAPOR (BETERRABA, VAGEM, CHUCHU E/OU CENOURA – 70G)",
      "COUVE FOLHA REFOGADO COM TOMATE, ALHO E CEBOLA ROXA A VONTADE OU SALADA GRUPO A À VONTADE",
      "CARNE BOVINA OU FRANGO AO MOLHO (2 COLHERES DE SERVIR – 100G) + 1 OVO COZIDO",
      "MOLHO DA SALADA: VINAGRE BALSAMICO, SAL ROSA, LIMÃO, ORÉGANO E AZEITE EXTRAVIRGEM OBS.: EVITAR FRITURA",
      "SOBREMESA: 100ML DE ÁGUA + SUCO DE 1 LIMÃO PEQUENO - CHÁ DE HORTELÃ OU GENGIBRE",
      "GRUPO A: (A VONTADE) ABOBRINHA, ALFACE, BERINJELA, BRÓCOLIS, CEBOLA, CEBOLINHA, COUVE, PALMITO, PEPINO, PIMENTÃO, REPOLHO, TOMATE",
      "GRUPO B: (DE ACORDO COM O PLANO) ABÓBORA, BETERRABA, CENOURA, CHUCHU, ERVILHA VERDE",
    ],
  },
  {
    id: "A7",
    alimentos: [
      "3 COLHERES DE SOPA DE PURÊ DE MACAXEIRA, BATATA INGLESA OU MANDIOQUINHA (GRUPO C – 90G)",
      "SALADA DE CENOURA, REPOLHO E CHEIRO VERDE REFOGADO (2 COLHERES GRANDES)",
      "COUVE FOLHA OU ESPINAFRE REFOGADOS COM TOMATE, ALHO E CEBOLA ROXA A VONTADE OU SALADA GRUPO A À VONTADE",
      "PEIXE OU FRANGO ASSADO OU GRELHADO (2 BIFES OU POSTAS PEQUENAS-120G)",
      "MOLHO DA SALADA: VINAGRE BALSAMICO, SAL ROSA, LIMÃO, ORÉGANO E AZEITE EXTRAVIRGEM OBS.: EVITAR FRITURA",
      "SOBREMESA: 100ML DE ÁGUA + SUCO DE 1 LIMÃO PEQUENO - CHÁ DE HORTELÃ OU ERVA DOCE",
      "GRUPO A: (A VONTADE) ABOBRINHA, ALFACE, BERINJELA, BRÓCOLIS, CEBOLA, CEBOLINHA, COUVE, PALMITO, PEPINO, PIMENTÃO, REPOLHO, TOMATE",
      "GRUPO C: (COM MODERAÇÃO DE ACORDO COM O PLANO) BATATA INGLESA, BATATA DOCE, MANDIOCA, MILHO VERDE",
    ],
  },
  {
    id: "LT1",
    alimentos: [
      "30G DE WHEY BATIDO COM 1 POLPA DE FRUTAS CONGELADA (MORANGO, AMORA, GOIABA ETC) + ÁGUA",
      "5G DE CREATINA",
    ],
  },
  {
    id: "LT2",
    alimentos: [
      "30G DE WHEY BATIDO COM 1 BANANA E ÁGUA GELADA",
      "5G DE CREATINA",
    ],
  },
  {
    id: "LT3",
    alimentos: [
      "3 FATIAS DE PÃO INTEGRAL + 3 COLHERES DE SOPA CHEIAS DE PATÊ CASEIRO DE ATUM OU FRANGO (MISTURAR 1 COLHER DE SOPA CHEIA DE CREME DE RICOTA OU COTTAGE LACFREE COM 3 COLHERES DE SOPA DE FRANGO DESFIADO OU ATUM EM CONSERVA DE AZEITE EXTRAVIRGEM + SAL, TEMPEROS NATURAIS E ORÉGANO)",
      "OU",
      "VITAMINA DE BANANA: 30G DE WHEY + 3 COLHERES DE SOPA DE GRANOLA + 1 BANANA GRANDE + ÁGUA GELADA",
    ],
  },
  {
    id: "LT4",
    alimentos: [
      "30G DE WHEY BATIDO COM 1 POLPA DE FRUTAS CONGELADA (MORANGO, AMORA, GOIABA ETC) + ÁGUA",
      "5G DE CREATINA",
    ],
  },
  {
    id: "LT5",
    alimentos: [
      "1 CUSCUZ DE MILHO PEITINHO MÉDIO (140G)",
      "2 OVOS MEXIDOS COM 3 COLHERES DE SERVIR DE FRANGO DESFIADO (80G) + TOMATE, CEBOLA E TEMPEROS NATURAIS",
      "OU",
      "1 TAPIOCA MÉDIA (70G – 4 COLHERES DE SOPA) COM MANTEIGA + RECHEIO DE 2 OVOS + 40G DE QUEIJO MUÇARELA ZERO LACTOSE",
    ],
  },
  {
    id: "LT6",
    alimentos: [
      "30G DE WHEY BATIDO COM ½ MAMÃO OU 3 AMEIXAS SECAS SEM CAROÇO E ÁGUA GELADA",
      "5G DE CREATINA",
    ],
  },
  {
    id: "LT7",
    alimentos: [
      "5G DE CREATINA BATIDO EM 200ML DE ÁGUA",
      "30 G DE WHEY BATIDO COM 1 BANANA E ÁGUA GELADA",
    ],
  },
  {
    id: "J1",
    alimentos: [
      "OMELETE DE 3 OVOS COM 4 COLHERES DE SOPA DE ATUM OU FRANGO DESFIADO+ ESPINAFRE+ CENOURA+CHEIRO VERDE+ SAL E TEMPERO SECO",
      "*PODERÁ FAZER OS OVOS MEXIDOS COM CARNE SECA OU FRANGO DEASFIADO TAMBÉM",
    ],
  },
  {
    id: "J2",
    alimentos: [
      "150G DE CARNE, PEIXE OU FRANGO",
      "SALADA DE VEGETAIS GRUPO A (FOLHAS A VONTADE+ TOMATE, CEBOLA, PEPINO, CENOURA RALADA ETC)",
      "FIO DE AZEITE EXTRAVIRGEM",
      "GRUPO A: (A VONTADE) ABOBRINHA, ALFACE, BERINJELA, BRÓCOLIS, CEBOLA, CEBOLINHA, COUVE, PALMITO, PEPINO, PIMENTÃO, REPOLHO, TOMATE",
    ],
  },
  {
    id: "J3",
    alimentos: [
      "ESPAGUETE DE ABOBRINHA COM CENOURA A VONTADE",
      "7 COLHERES DE SOPA DE CARNE MOÍDA – 140G",
    ],
  },
  {
    id: "J4",
    alimentos: [
      "OMELETE DE 3 OVOS COM 4 COLHERES DE SOPA DE ATUM OU FRANGO DESFIADO+ ESPINAFRE+ CENOURA+CHEIRO VERDE+ SAL E TEMPERO SECO",
      "*PODERÁ FAZER OS OVOS MEXIDOS COM CARNE SECA OU FRANGO DEASFIADO TAMBÉM",
    ],
  },
  {
    id: "J5",
    alimentos: [
      "150G DE CARNE, PEIXE OU FRANGO",
      "SALADA DE VEGETAIS GRUPO A (FOLHAS A VONTADE+ TOMATE, CEBOLA, PEPINO, CENOURA RALADA ETC)",
      "FIO DE AZEITE EXTRAVIRGEM",
      "GRUPO A: (A VONTADE) ABOBRINHA, ALFACE, BERINJELA, BRÓCOLIS, CEBOLA, CEBOLINHA, COUVE, PALMITO, PEPINO, PIMENTÃO, REPOLHO, TOMATE",
    ],
  },
  {
    id: "J6",
    alimentos: [
      "ESPAGUETE DE ABOBRINHA COM CENOURA A VONTADE",
      "7 COLHERES DE SOPA DE CARNE MOÍDA – 140G",
    ],
  },
  {
    id: "J7",
    alimentos: [
      "OMELETE DE 3 OVOS COM 4 COLHERES DE SOPA DE ATUM OU FRANGO DESFIADO+ ESPINAFRE+ CENOURA+CHEIRO VERDE+ SAL E TEMPERO SECO",
      "*PODERÁ FAZER OS OVOS MEXIDOS COM CARNE SECA OU FRANGO DEASFIADO TAMBÉM",
    ],
  },
];
